#!/usr/bin/env bash
# Copyright (C) 2016 iNuron NV
#
# This file is part of Open vStorage Open Source Edition (OSE),
# as available from
#
#      http://www.openvstorage.org and
#      http://www.openvstorage.com.
#
# This file is free software; you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License v3 (GNU AGPLv3)
# as published by the Free Software Foundation, in version 3 as it comes
# in the LICENSE.txt file of the Open vStorage OSE distribution.
#
# Open vStorage is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY of any kind.

cd /opt/asd-manager
export PYTHONPATH="${PYTHONPATH}:/opt/asd-manager"
export DISPLAY=:0

function show_help {
    echo "ASD Manager CLI launcher"
    echo "------------------------"
    echo "Usage:"
    echo "  * Miscellaneous options:"
    echo "    - asd-manager help                  Show this help section"
    echo ""
    echo "  * Setup options:"
    echo "    - asd-manager setup                 Launch ASD Manager setup"
    echo ""
    echo "  * Remove options:"
    echo "    - asd-manager remove                Remove the ASD Manager from this node"
    echo ""
    echo "  * Monitor options:"
    echo "    - asd-manager monitor services      Watch ASD Manager services"
}

if [ "$1" = "monitor" ] ; then
    if [ "$2" = "services" ] ; then
        service_manager=`cat /proc/1/comm`
        if test "$service_manager" = "systemd"
        then
            watch -n 1 'echo "\nASD Manager running processes:\n";systemctl -l| grep alba | grep "loaded active" | sort;echo "\nASD Manager non-running processes:\n";systemctl -l | grep alba | grep -v "loaded active" | sort'
        else
            watch -n 1 'echo "\nASD Manager running processes:\n";initctl list | grep alba | grep start/running | sort;echo "\nASD Manager non-running processes:\n";initctl list | grep alba | grep -v start/running | sort'
        fi
    else
        show_help
    fi
elif [ "$1" = "setup" ] ; then
    python -c "from source.asdmanager import setup; setup()"
elif [ "$1" = "remove" ] ; then
    python -c "from source.asdmanager import remove; remove('$2')"
else
    show_help
fi
