#!/usr/bin/env bash
# Copyright (C) 2016 iNuron NV
#
# This file is part of Open vStorage Open Source Edition (OSE),
# as available from
#
#      http://www.openvstorage.org and
#      http://www.openvstorage.com.
#
# This file is free software; you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License v3 (GNU AGPLv3)
# as published by the Free Software Foundation, in version 3 as it comes
# in the LICENSE.txt file of the Open vStorage OSE distribution.
#
# Open vStorage is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY of any kind.

cd /opt/asd-manager
export PYTHONPATH="${PYTHONPATH}:/opt/asd-manager"
export DISPLAY=:0

function show_help {
    echo "ASD Manager CLI launcher"
    echo "------------------------"
    echo "Usage:"
    echo "  * Miscellaneous options:"
    echo "    - asd-manager help                  Show this help section"
    echo "    - asd-manager collect logs          Collect all ASD Manager logs to a tarball (for support purposes)"
    echo ""
    echo "  * Setup options:"
    echo "    - asd-manager setup                 Launch ASD Manager setup"
    echo ""
    echo "  * Remove options:"
    echo "    - asd-manager remove                Remove the ASD Manager from this node"
    echo ""
    echo "  * Monitor options:"
    echo "    - asd-manager monitor services      Watch ASD Manager services"
    echo ""
    echo "  * Run automated local update:"
    echo "    - asd-manager local_update alba             Execute a local update of alba and its dependencies"
    echo ""
}

if [ "$1" = "monitor" ] ; then
    if [ "$2" = "services" ] ; then
        python -c "from source.tools.servicefactory import ServiceFactory; service_manager = ServiceFactory.get_manager(); service_manager.monitor_services()"
    else
        show_help
    fi
elif [ "$1" = "setup" ] ; then
    python -c "from source.asdmanager import setup; setup()"
elif [ "$1" = "remove" ] ; then
    python -c "from source.asdmanager import remove; remove('$2')"
elif [ "$1" = "collect" ] ; then
    if [ "$2" = "logs" ] ; then
        FILENAME=asdmanager-`hostname`-`date "+%Y%m%d%H%M%S"`-logs.tar
        LOGFILE=/opt/asd-manager/downloads/${FILENAME}
        rm -f ${LOGFILE}
        rm -f ${LOGFILE}.gz
        touch ${LOGFILE}
        journalctl -u asd-* -u alba-* --no-pager > /var/log/journald.log 2>&1 || true
        tar uvf ${LOGFILE} /var/log/upstart/alba-* > /dev/null 2>&1
        tar uvf ${LOGFILE} /var/log/upstart/asd-* > /dev/null 2>&1
        tar uvf ${LOGFILE} /var/log/*log > /dev/null 2>&1
        tar uvf ${LOGFILE} /var/log/dmesg* > /dev/null 2>&1
        gzip ${LOGFILE} > /dev/null
        echo ${FILENAME}.gz
    else
        show_help
    fi
elif [ "$1" = "local_update" ] ; then
    if [ "$2" = "alba" ] ; then
            python -c """
from ovs.lib.update.albacomponent_update import AlbaComponentUpdater
from ovs.extensions.generic.system import System
AlbaComponentUpdater.do_update(System.get_my_machine_id())
"""
    else
        show_help
    fi
else
    show_help
fi
